# Generated by Django 3.0.7 on 2020-08-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larcauth', '0010_auto_20200815_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluation',
            old_name='nb_marksup',
            new_name='nb_mark',
        ),
        migrations.RenameField(
            model_name='evaluation',
            old_name='nb_marksup_a',
            new_name='nb_mark_a',
        ),
        migrations.RenameField(
            model_name='evaluation',
            old_name='nb_marksup_b',
            new_name='nb_mark_b',
        ),
        migrations.RenameField(
            model_name='evaluation',
            old_name='nb_marksup_c',
            new_name='nb_mark_c',
        ),
        migrations.RenameField(
            model_name='evaluation',
            old_name='nb_marksup_d',
            new_name='nb_mark_d',
        ),
        migrations.RenameField(
            model_name='evaluation',
            old_name='nb_marksup_e',
            new_name='nb_mark_e',
        ),
        migrations.RenameField(
            model_name='evaluation',
            old_name='nb_marksup_f',
            new_name='nb_mark_f',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='maxim',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='maxim_a',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='maxim_b',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='maxim_c',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='maxim_d',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='maxim_e',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='maxim_f',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='minim',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='minim_a',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='minim_b',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='minim_c',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='minim_d',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='minim_e',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='minim_f',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='stddev',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='stddev_a',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='stddev_b',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='stddev_c',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='stddev_d',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='stddev_e',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='stddev_f',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='all_grades',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='all_grades_a',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='all_grades_b',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='all_grades_c',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='all_grades_d',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='all_grades_e',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='all_grades_f',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
