# Generated by Django 3.0.7 on 2020-08-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larcauth', '0011_auto_20200819_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_has_termsubjeval',
            name='id_big',
            field=models.BigIntegerField(null=True),
        ),
    ]
