# Generated by Django 3.0.7 on 2020-08-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larcauth', '0012_student_has_termsubjeval_id_big'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_has_termsubjeval',
            name='id',
        ),
        migrations.AlterField(
            model_name='student_has_termsubjeval',
            name='id_big',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
