# Generated by Django 3.0.7 on 2020-08-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larcauth', '0014_auto_20200821_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='auto_calc',
            field=models.BooleanField(default=True),
        ),
    ]
