# Generated by Django 3.0.7 on 2020-08-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larcauth', '0016_auto_20200824_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_log',
            name='id_big',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
