# Generated by Django 3.0.7 on 2020-10-16 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('larcauth', '0017_auto_20200824_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='aecuser',
            name='fk_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='larcauth.parentutor'),
        ),
    ]
