# Generated by Django 3.0.7 on 2020-10-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larcauth', '0018_aecuser_fk_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_has_termsubjeval',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
