# Generated by Django 3.0.7 on 2020-12-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larcauth', '0021_evaluation_fk_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerdp_has_termsubjectdp',
            name='ei_observation',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
