# Generated by Django 3.0.7 on 2021-05-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larcauth', '0023_api_studentdp_has_termsubjectdp'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_studentdp_has_termsubjectdp',
            name='date_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_studentdp_has_termsubjectdp',
            name='i_studentid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='api_studentdp_has_termsubjectdp',
            name='i_subjectid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='api_studentdp_has_termsubjectdp',
            name='i_term',
            field=models.SmallIntegerField(null=True),
        ),
    ]
